version: '3.9'

services:
  app:
    build: .
    container_name: ewally_node
    restart: always
    ports:
      - 8080:8080
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
